### ISSUE TITLE
Appeals: fees are always refunded to appeal confirmer if no juror was coherent

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#101]
The new adjudication round is [created in `appealConfirm`](https://github.com/aragon/aragon-court/blob/b97df5ce134620d0692f56ee185b5a003e8ecd83/contracts/Court.sol#L466) which sets `msg.sender` as the entity that triggered the appeal:

https://github.com/aragon/aragon-court/blob/b97df5ce134620d0692f56ee185b5a003e8ecd83/contracts/Court.sol#L1008

This makes sense for the initial round, as if no juror voted for the final ruling, it makes sense to refund the fees to whoever paid to start the dispute. For appeal rounds, there is no reason for whoever confirmed the appeal to always be the one that is refunded (even if they lost their deposit for supporting the wrong ruling). 

 In case that none of the jurors drafted in the appeal round, we should 'refund' the juror fees in `settleAppealDeposit`, which in practice would be not deducting the fees when returning the deposit.

**Comment by facuspagnuolo** [comment]
I follow the problem but not sure what's the solution you propose. Do you mean, splitting the juror fees between the appeal maker and the taker?

**Comment by izqui** [comment]
Either doing that (which would be more similar to what we do in round #1), or sending the collected fees to the subscription pool so that they are split among all active jurors
