### ISSUE TITLE
Court: bounds for initial juror number when creating a dispute

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#106]
There is currently a to-do for limiting the max number of initial jurors, but we should also require a minimum of 1 juror for creating the dispute. A dispute with 0 jurors would revert when drafting, and even if it probably doesn't create an issue for the Court outside of this dispute, we should prevent it from happening in the first place.

Setting a very high number of initial jurors would make appeals really expensive, as the total number of appeal rounds before getting to the final round is fixed.

Another option is to make the initial number of jurors a configuration parameter, so creators of a dispute don't have the ability to decide. A counter argument to this would be that having the option to set the initial juror number allows the creator of a dispute to start with more or less 'security' and more certainty that the dispute will be finalized sooner.

**Comment by facuspagnuolo** [comment]
Related to https://github.com/aragon/aragon-court/issues/126

**Comment by facuspagnuolo** [comment]
@izqui WDYT about going for the setting instead?

**Comment by izqui** [comment]
I'd add the setting, then we can close this :)
