### ISSUE TITLE
Court: Upgradeability/Recoverability mechanism 

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/aragon-court#121]
The court will not be necessarily upgradeable. However, it may be interesting to start thinking about what should be the flow in case we need to shut down the court, migrate it to another contract, fork into separate contracts, or any other similar situation. We should think at least what will be the interface at least the users can rely on.

**Comment by facuspagnuolo** [comment]
I've been thinking on this issue for a while, here is a summary of what I could come up with:

## Problem

The Court is currently split into ~5 modules, where all of them depend somehow on one another. Additionally, at least 3 of them (main court, subscriptions, and registry) have core settings, critical to their functionality, that can be adjusted by a "governor". Finally, some of these modules manipulate/store token assets. 

Being pessimist, I'd love to see a recoverability mechanism we can use to plug/unplug these modules in case we need to improve or fix sth. We basically need to solve 3 problems here:
- Have a way to change each modules' core settings (halfway implemented)
- Have a way to change the governor (missing)
- Have a way to recover/transfer the token assets to other instances
- Have a way to "eject" the governor role from the whole protocol

## Solution (Part I)

We can have a simple reusable contract that holds the logic the "governor" can execute on these modules:

```js
contract Governed {
    string private constant ERROR_SENDER_NOT_GOVERNOR = "GVD_SENDER_NOT_GOVERNOR";
    string private constant ERROR_INVALID_GOVERNOR_ADDRESS = "GVD_INVALID_GOVERNOR_ADDRESS";
    string private constant ERROR_RECOVER_TOKEN_FUNDS_FAILED = "GVD_RECOVER_TOKEN_FUNDS_FAILED";

    address private constant ETH = address(0);
    address private constant NO_GOVERNOR = address(0);

    address public governor;

    event RecoverFunds(address token, address recipient, uint256 balance);
    event GovernorChanged(address previousGovernor, address currentGovernor);

    modifier onlyGovernor {
        require(msg.sender == governor, ERROR_SENDER_NOT_GOVERNOR);
        _;
    }

    constructor (address _governor) public {
        governor = _governor;
    }

    function changeGovernor(address _newGovernor) external onlyGovernor {
        require(_newGovernor != NO_GOVERNOR, ERROR_INVALID_GOVERNOR_ADDRESS);
        _setGovernor(_newGovernor);
    }

    function eject() external onlyGovernor {
        _setGovernor(NO_GOVERNOR);
    }

    function recoverFunds(address _token, address payable _to) external onlyGovernor {
        uint256 balance;
        if (_token == ETH) {
            balance = address(this).balance;
            _to.transfer(balance);
        } else {
            ERC20 token = ERC20(_token);
            balance = token.balanceOf(address(this));
            require(token.transfer(_to, balance), ERROR_RECOVER_TOKEN_FUNDS_FAILED);
        }
        emit RecoverFunds(_token, _to, balance);
    }

    function _setGovernor(address _newGovernor) private {
        emit GovernorChanged(governor, _newGovernor);
        governor = _newGovernor;
    }
}
```

This will allow us to share the "governor" knowledge among all these modules. We can use it during the initialization, or to control the core settings changes flow:

```js
contract X is Governed {
    struct Config {
        uint256 a;
        address b;
        bool c;
    }

    Config public config;

    function init(uint256 _a, address _b, bool _c) external onlyGovernor {
        config = Config({ a: _a, b: _b, c: _c });
    }

    function setConfig(uint256 _a, address _b, bool _c) external onlyGovernor {
        config = Config({ a: _a, b: _b, c: _c });
    }
}

contract Y is Governed {
    X public x;

    function init(X _x) external onlyGovernor {
        x = _x;
    }

    function setX(X _x) external onlyGovernor {
        x = _x;
    }
}
```

## Solution (Part II)

Finally, a second thought on this topic is to model a "governor" contract. This will allow to manipulate the "governees" (`Governed`) all at once. Ofc it could provide simplicity, but I was thinking of a potential case where we need to apply multiple changes at once, e.g. switching multiple instances to avoid having an inconsistent state in the middle.

```js
contract Governor is Governed {
    string private constant ERROR_INVALID_GOVERNED_INDEX = "GVR_INVALID_GOVERNED_INDEX";
    string private constant ERROR_GOVERNED_EXECUTION_FAILED = "GVR_GOVERNED_EXECUTION_FAILED";

    Governed[] public governedList;

    event GovernedAdded(address governed);
    event GovernedEjected(address governed);
    event GovernedExecuted(address governed, bytes data);
    
    function initialize(X _x, Y _y, uint256 _a, address _b, bool _c) external onlyGovernor {
        _govern(_x);
        _govern(_y);

        _x.init(_a, _b, _c);
        _y.init(_x);
    }

    function govern(Governed _governed) external onlyGovernor {
        _govern(_governed);
    }

    function ejectAll() external onlyGovernor {
        for (uint256 i = governedList.length; i > 0; i--) {
            _ejectLast();
        }
    }

    function ejectAt(uint256 _index) external onlyGovernor {
        require(_index < governedList.length, ERROR_INVALID_GOVERNED_INDEX);
        _swapLast(_index);
        _ejectLast();
    }

    function executeMany(uint256[] calldata _indexes, bytes[] calldata _data) external onlyGovernor {
        for (uint256 i = 0; i < _indexes.length; i++) {
            _executeAt(_indexes[i], _data[i]);
        }
    }

    function executeAt(uint256 _index, bytes calldata _data) external onlyGovernor {
        _executeAt(_index, _data);
    }

    function _govern(Governed _governed) private {
        governedList.push(_governed);
        emit GovernedAdded(address(_governed));
    }
    
    function _ejectLast() private {
        Governed last = governedList[governedList.length - 1];
        governedList.length--;
        emit GovernedEjected(address(last));
    }

    function _swapLast(uint256 _index) private {
        uint256 lastIndex = governedList.length - 1;
        Governed last = governedList[lastIndex];
        governedList[lastIndex] = governedList[_index];
        governedList[_index] = last;
    }

    function _executeAt(uint256 _index, bytes memory _data) private {
        require(_index < governedList.length, ERROR_INVALID_GOVERNED_INDEX);

        address governed = address(governedList[_index]);
        emit GovernedExecuted(governed, _data);
        (bool success,) = governed.delegatecall(_data);
        require(success, ERROR_GOVERNED_EXECUTION_FAILED);
    }
}
```

## Little extra

As you may have noticed, this will allow us to move all the initialization logic to the `Controller` removing it from the `Court` contract as we are doing now (related to #78).

----

cc @bingen @izqui would love your thoughts on this one

**Comment by izqui** [comment]
Thanks for pushing this @facuspagnuolo.

I really like the `Governed` abstraction and we should definitely add it to all the modules.

I don't think the `Governor` concept is needed. As the Court's governor will likely be an Aragon DAO (through an Agent) anyway, multiple configuration changes can be done atomically in one transaction using a CallsScript with multiple Agent `execute` invocations.

> at least 3 of them (main court, subscriptions, and registry) have core settings, critical to their functionality, that can be adjusted by a "governor"

This lead me to thinking about whether we should centralize all configuration into its own module, and maybe also create a 'registry module' that allows modules to find the address of other modules by an ID (rather than saving references in each module).

**Comment by facuspagnuolo** [comment]
@izqui thanks for sharing your thoughts! 

Agreed with your opinion in favor of using an Agent instance instead of having a Governor one, good point. 

Regarding the idea of having a registry or similar for discoverability, I think it could be super useful. Will try to analyze it a bit more and see if I can come up with something else :)

**Comment by bingen** [comment]
Looking good. I agree, I like the `Governed` but I don't see `Governor` as necessary.
About the centralized config, not sure yet, I'll think about it a little bit more.
