### ISSUE TITLE
Court: Move appeal factors to court settings

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/aragon-court#125]
Move `Court` constants `APPEAL_COLLATERAL_FACTOR` and `APPEAL_CONFIRMATION_COLLATERAL_FACTOR` to `CourtSettings`

**Comment by facuspagnuolo** [comment]
Closed by https://github.com/aragon/aragon-court/pull/146

**Comment by bingen** [comment]
TIL: github's grammar knowledge is limited, so if you say "Fixes #106, #125 and #126", it will only fix the first one, but the other two will remain open. :joy: 
Thanks @facuspagnuolo for doing it for me! :wink:
