### ISSUE TITLE
Chore: Pre-push hook runs only for the local checked out branch

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#144]
but what user has locally instead, no matter if it hasn't been committed yet.
(See https://github.com/aragon/aragon-court/pull/128 for reference)

**Comment by facuspagnuolo** [comment]
Not sure what's the issue, would you mind adding some steps to reproduce it?

**Comment by bingen** [comment]
Yes sure:

1- Make some changes that break linter, commit and try to push them. You won't be able because `npm run lint` will fail.
2- Fix the issues reported by linter, but without committing those changes (just saving them locally in your files).
3- Run `git push` now, it will work, but you will still be pushing the code in [1], which was wrong.

**Comment by facuspagnuolo** [comment]
I see, but I think it will be quite cumbersome to run the linter only for committed changes. Don't know if there is another githook that actually does that. However, the idea was simply to prevent us from waiting for 1.5 hs to know if the CI failed or not, you can also skip the githooks and push if you want 🤷‍♂

**Comment by facuspagnuolo** [comment]
Closing this issue for now
