### ISSUE TITLE
Prevent drafts happening without a randomness seed

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#15]
Right now, if the first draft of a term happens more than 256 blocks after the term starts, the blockhash that will be returned for the `randomnessBN` of the term will be 0.

Options to work around this problem:

- Treat this as a round being drafted in the wrong term and require rescheduling as in #14 
- Implement a secondary `heartbeat()` function (which can be called one block after the actual `heartbeat`) that stores the `randomness` for the term. The caller could get the current `dependingDrafts * heartbeatFee` that is being paid to the `heartbeat()` caller and pay heartbeat fees just from activation, updates and deactivation fees (#7)

**Comment by bingen** [comment]
I think both options are complementary and that even if we implemented the second one we would still need the first one to make sure we have proper randomness.
Besides now we already are able to delay draft to later terms (#44), so I'm going to do the first one and we can still add the extra heartbeat function later.

**Comment by facuspagnuolo** [comment]
Closed by https://github.com/aragon/aragon-court/pull/58
