### ISSUE TITLE
Chore: Add JS linter for tests

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/aragon-court#154]

**Comment by sohkai** [comment]
So excited to do this :).

I am **absolutely** going to publish Aragon linter configs late this week or early next week so we'll be able to do this everywhere :).

**Comment by sohkai** [comment]
> I am absolutely going to publish Aragon linter configs late this week or early next week so we'll be able to do this everywhere :).

Clearly this has not happened 😉. We can re-update this when we do make the shared config.
