### ISSUE TITLE
Registry: Drafting could result in an OOG error

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/aragon-court#157]
Since we are using a random seed to fetch a number of jurors from the tree and these need to have enough active balance to be selected for a draft, this function may never end. Thus, we may want to cap the number of iterations to avoid having OOG errors. However, limiting the iterations could trigger some consequences. For instance, we may want to handle this from the `Court` contract, which may lead us to start thinking that further rounds could have fewer jurors drafted than previous ones.

**Comment by bingen** [comment]
This is related to #62
