### ISSUE TITLE
Court: Implement more getters to fetch state

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#16]
Right now most of the Court's state can be reconstructed checking the logs of the contract, but we should provide some getters (`external view`s) that allow for quickly fetching the state of a dispute, adjudication round and juror accounts.

**Comment by facuspagnuolo** [comment]
Multiple getters were already added to fetch configs, dispute, round, and appeal states. However, many state variables are still `internal` without a getter, we should probably want to either provide a getter if we don't reach the contract size limit or make them `pubilc`
