### ISSUE TITLE
Jurors Registry: future deactivation vs present draft

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#187]
I wonder what's exactly the point of deactivation in the future (next term). I thought the idea was to keep terms consistent so active tokens and therefore drafts probability don't change in the middle of a term.
But with this:
https://github.com/aragon/aragon-court/blob/development/contracts/registry/JurorsRegistry.sol#L727
if a juror sends a full deactivation request during term `t`, the juror won't be able to withdraw until term `t+1`, but won't be either be able to be drafted during term `t`.
I see 2 solutions here:

- Deactivate immediately. This would improve juror UX, as funds would be immediately available and deactivation and withdrawal could happen in the same transaction, but it would miss the aforementioned point of term integrity.
- Lowering next term deactivation request amount, instead of just checking it. I would go for this one as I think it was the initial intention.

**Comment by facuspagnuolo** [comment]
Nice catch, I was completely sure we were doing the same as in `collectTokens` (see [here](https://github.com/aragon/aragon-court/blob/development/contracts/registry/JurorsRegistry.sol#L298-L315)). Let's apply the same logic for the draft
