### ISSUE TITLE
Contracts: Use SafeMath for balance updates

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#22]
For instance: 
https://github.com/aragonone/aragon-court/blob/778ab8b28f93911940152f4925acd57f3ad2f4a1/contracts/Court.sol#L969
https://github.com/aragonone/aragon-court/blob/778ab8b28f93911940152f4925acd57f3ad2f4a1/contracts/Court.sol#L1039
https://github.com/aragonone/aragon-court/blob/778ab8b28f93911940152f4925acd57f3ad2f4a1/contracts/Court.sol#L1045
https://github.com/aragonone/aragon-court/blob/778ab8b28f93911940152f4925acd57f3ad2f4a1/contracts/Court.sol#L1051

Or if we are completely sure that those can not over/underflow due to the inner logic, add a comment explaining it.

**Comment by bingen** [comment]
SafeMath should be considered for `_signedSum` too. Btw, I find easier to understand (and in my tests with Remix slightly cheaper) this way:
```
function _signedSum(uint256 nA, bool pA, uint256 nB, bool pB) public pure returns (uint256 nC, bool pC) {
        int256 a = int256(pA ? nA : -nA);
        int256 b = int256(pB ? nB : -nB);
        int256 c = a + b;
        pC = c >= 0;
        nC = uint256(pC ? c : -c);
    }
```
Main downside is losing one bit, but `2^128` still seems enough (should be checked too).

**Comment by facuspagnuolo** [comment]
Related to #47
