### ISSUE TITLE
Add linter and fix linting issues

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#23]
We use solium in other repos, see aragonOS' config for reference: https://github.com/aragon/aragonOS/blob/dev/.soliumrc.json

**Comment by bingen** [comment]
This is already done [here](https://github.com/aragon/aragon-court/pull/41/commits/37b8d8f541ddf164bf2848187e25b9bf14108441) and [here](https://github.com/aragon/aragon-court/pull/41/commits/d3615ab7acf1534dfa9adad74871cd31b3b5f648).
I will close it when it's merged.
