### ISSUE TITLE
Allow to activate with pending deactivations

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#247]
When activating, processing deactivation pending requests should happen before checking available balance. See:

https://github.com/aragon/aragon-court/blob/master/contracts/registry/JurorsRegistry.sol#L147
https://github.com/aragon/aragon-court/blob/master/contracts/registry/JurorsRegistry.sol#L150
https://github.com/aragon/aragon-court/blob/master/contracts/registry/JurorsRegistry.sol#L563

**Comment by izqui** [comment]
It seems like this is just a UX issue and not a bug in the smart contract per se

**Comment by bingen** [comment]
Yes, it's definitely a UX issue. Users can call `processDeactivationRequest` or `withdraw` first.

**Comment by izqui** [comment]
While a tiny bit inconvenient, I recommend not fixing and releasing a new version right now, as it is not a security vulnerability and it can be easily fixed at the client level.

In my opinion, a good fix would be for this to be detected by clients and if a juror wants to activate tokens and they have a pending deactivation, they would be prompted to sign and execute two transactions, the first one to `processDeactivationRequest` and right after perform the activation.

Another option proposed offline would be to run a service that would send `processDeactivationRequest` for all deactivation requests, which I consider unnecessary given that most deactivations will be done by jurors on they way out and deactivations are properly processed when unstaking.
