### ISSUE TITLE
UI/UX of buying more ANJ as a Juror

### ISSUE THREAD

**Issue by LukeWheeldon** [aragon/aragon-court#266]
A Juror navigating on court.aragon.org/dashboard and wishing to acquire more ANJ would hit "Buy ANJ", to then find themselves on anj.aragon.org, which place is mostly for people who are not yet Jurors.

I would suggest to direct that "Buy ANJ" button to convert.aragon.org as that would make more sense and would be an easy fix. With that said, anj.aragon.org is more flexible in the input tokens it accepts. I might be wrong, but I imagine most Jurors who would want to buy more ANJ, would more often do so with either ETH or DAI. Ultimately then, convert.aragon.org should probably also accept ETH and DAI.

**Comment by sohkai** [comment]
Thanks for the feedback @LukeWheeldon!

> With that said, anj.aragon.org is more flexible in the input tokens it accepts. I might be wrong, but I imagine most Jurors who would want to buy more ANJ, would more often do so with either ETH or DAI. Ultimately then, convert.aragon.org should probably also accept ETH and DAI.

Indeed, these are aspects we've considered in our decision making and for now, have decided to keep the link pointing to `anj.aragon.org` for those reasons. We are very interested in improving convert.aragon.org with the ability to use other tokens, as well as have it be a smarter converter, but have chosen not to prioritize it in the near term.

I'll close this issue for now. We are aware of its shortcomings—we are just not able to improve it at this moment.
