### ISSUE TITLE
Court: Add term limits to config changes 

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#36]
- Enforce that config changes need to be scheduled at least a certain number of terms in advance. This limit (`MIN_SCHEDULE_CONFIG_CHANGE_TERMS`) should be a constant in the Court and needs to be higher or equal to the number of terms that a dispute (or appeal round) can be scheduled in advance.

- At the moment when changing the config, if there was already a scheduled config change, it is overridden by the new incoming config. This can be problematic if the term in which the config was scheduled to change is close enough to the current term that there can be disputes or appeal rounds initiated with the fee schedule of a future config which can be cancelled by scheduling a new config change. Config changes shouldn't be possible if there is a pending config change scheduled to happen in less than `MIN_SCHEDULE_CONFIG_CHANGE_TERMS`

**Comment by facuspagnuolo** [comment]
Remember to use the same limit for the creation of a dispute, we have to ensure future drafts term ids are not after a possible config change
