### ISSUE TITLE
Contracts: Stack too deep issues

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#43]
Fix stack too deep issues in Court contract:

- `draftAdjudicationRound`
- `settleRoundSlashing`

Once it's fixed, optimize `SSTORE` and `SLOAD` use.

See comments [here](https://github.com/aragon/aragon-court/pull/41#discussion_r285199861) and [here](https://github.com/aragon/aragon-court/pull/41#discussion_r285199452) for more context.

**Comment by izqui** [comment]
Do we want to get this in for the freeze?
