### ISSUE TITLE
Court: Expose external config setter

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#53]
Currently it is just an internal function used to set the initial configuration, but the `governor` should be able to change the config. 

There should be a threshold of terms during which no config changes are allowed, if there is an incoming configuration change happening within the threshold, a configuration change overriding it should not be allowed either.

The logic for changing the config after setting it for the first time should also be reviewed, as I believe that both https://github.com/aragon/aragon-court/blob/24cb0916000f9b479842e810485330715c45f671/contracts/Court.sol#L1094 and https://github.com/aragon/aragon-court/blob/24cb0916000f9b479842e810485330715c45f671/contracts/Court.sol#L1119 should use `_fromTermId` instead of `configChangeTermId`

**Comment by facuspagnuolo** [comment]
Add the appeal step factor to the court settings as well instead of using the `APPEAL_STEP_FACTOR` constant

**Comment by facuspagnuolo** [comment]
Related to https://github.com/aragon/aragon-court/issues/90

**Comment by facuspagnuolo** [comment]
Related to https://github.com/aragon/aragon-court/issues/127

**Comment by bingen** [comment]
Yes, I think this is wrong, but as it was only being used on init we didn't realize.
