### ISSUE TITLE
Jurors can vote in the final round without being slashed if they are in the losing side

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#70]
Look here:
https://github.com/aragon/aragon-court/blob/split_staking_3/contracts/Court.sol#L646
and here:
https://github.com/aragon/aragon-court/blob/split_staking_3/contracts/Court.sol#L656
Let's say that `jurorMinStake = 10`, that `FINAL_ROUND_WEIGHT_PRECISION = 1000`, that juror stake was 9 and `penalytPct` is 10%. 
Then first line will give: `weight = 1000*9/10 = 900`.  
Weight will be >0, so it will get into the 2nd one, which will give:
`weightedPenalty = 10*10/100 * 900 / 1000 = 1 * 900 / 1000 = 0` (due to Solidity rounding).
So it will be able to vote but it won't be slashed at all.

**Comment by facuspagnuolo** [comment]
Closed by #71
