### ISSUE TITLE
Explore ways to split Court into multiple contracts

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-court#8]
For simplicity, the Court implementation has been done in just one contract as the state of the contract is quite interdependent between most parts of the mechanism. An idea for separating concerns would be to split the general court state from the dispute management and adjudication.

We are still well below the block gas limit (at the moment ~5.5m gas), but as we keep implementing new functionality, we will start approaching the limit.

**Comment by bingen** [comment]
Update on this. Right now is an important issue, as the contract exceeds the maximum size allowed by [EIP-170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md).
I have explored several strategies to reduce its size, right now what seems to make more sense and be more effective is to split Commit-Reveal voting (bbranch `split_voting`) and SumTree (branch `split_sumtree`).

I attach here some tools I have used for analyzing this.

- Function calls graph generated wih [surya](https://github.com/ConsenSys/surya):
- Disassembled bytecode generated with [ethervm](https://ethervm.io/decompile) and with some function entry points sprinkled. (Might try [ethersplay](https://github.com/crytic/ethersplay) in future iterations)
- Spreadsheet with estimations of most functions size.

 
[Court_analysis.tar.gz](https://github.com/aragon/aragon-court/files/3163100/Court_analysis.tar.gz)

Right now the current size came down from more than 26k to ~21.5k bytes, so it's under EIP requirement but there's no much margin left.
 
```
npx truffle compile > /dev/null && cat build/contracts/Court.json | jq '.bytecode' | wc -m | xargs -I {} echo "{} / 2 - 1" | bc
21524
```

**Comment by facuspagnuolo** [comment]
Closing this since we already implemented many paths to split the old Court logic in different contracts.
