### ISSUE TITLE
Court: Fix final round number of jurors inconsistency

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-court#97]
See:

https://github.com/aragon/aragon-court/blob/b71a78c5d7cb58869e120436b5d0b09e7d536917/contracts/Court.sol#L963

and:

https://github.com/aragon/aragon-court/pull/75#discussion_r311941562

**Comment by facuspagnuolo** [comment]
@bingen @izqui I think this one was already solved [here](https://github.com/aragon/aragon-court/pull/103/files?file-filters%5B%5D=.sol#diff-4bb317b489994cf6f4c4b7ed11c18590R1333-R1340), let me know if I can close it

**Comment by izqui** [comment]
Yup, it should be fixed. If we don't have an explicit test for it, it would be good to add it though :)
